"""Content Standard constants and statuses."""

CONTENT_STANDARD_STATUS_DRAFT = "draft"
CONTENT_STANDARD_STATUS_ACTIVE = "active"
CONTENT_STANDARD_STATUS_ARCHIVED = "archived"

CONTENT_STANDARD_STATUSES: frozenset[str] = frozenset(
    {
        CONTENT_STANDARD_STATUS_DRAFT,
        CONTENT_STANDARD_STATUS_ACTIVE,
        CONTENT_STANDARD_STATUS_ARCHIVED,
    }
)

DEFAULT_CONTENT_STANDARD_NAME = "Curionex Content Standard"
DEFAULT_CONTENT_STANDARD_VERSION = "1"
