"""Production Editorial Catalog seed (post-audit curation)."""

EDITORIAL_SEED_SOURCE = "curionex-production-catalog-v1"

# Legacy slug remaps applied by curation seed (old -> new).
SLUG_RENAME_MAP: dict[str, str] = {
    "axolotl-regeneration-superpower": "how-axolotls-regrow-brain-and-heart",
    "bioluminescent-waves-red-tide": "why-ocean-waves-glow-blue-at-night",
    "bone-stronger-than-steel": "why-bones-stronger-than-concrete",
    "brain-uses-20-percent-myth": "why-10-percent-brain-myth-is-wrong",
    "deepest-ocean-trench-pressure": "why-deepest-ocean-could-crush-submarine",
    "growth-vs-fixed-mindset": "why-believing-you-can-improve-changes-learning",
    "hard-drive-not-hallway": "how-hard-drive-reads-data-without-touching",
    "immortal-jellyfish-turritopsis": "how-immortal-jellyfish-reverses-aging",
    "immune-system-daily-fight": "what-immune-system-does-in-60-seconds",
    "jupiter-protects-earth-asteroids": "does-jupiter-protect-earth-from-asteroids",
    "mantis-shrimp-punch-speed": "why-mantis-shrimp-punches-faster-than-bullet",
    "microbiome-cells-outnumber-you": "why-gut-microbes-shape-digestion-immunity-mood",
    "mirror-neurons-empathy": "why-yawns-are-contagious",
    "speed-of-light-constant": "why-nothing-can-outrun-light",
    "tardigrade-extreme-survival": "how-tardigrades-survive-vacuum-of-space",
    "trees-communicate-fungal-network": "how-trees-share-nutrients-fungal-networks",
}

# Slugs soft-archived by curation (REMOVE + MERGE).
CURATION_ARCHIVE_SLUGS: frozenset[str] = frozenset(
    {
        "bernoulli-principle-flight",
        "cloud-storage-not-clouds",
        "lincoln-vampire-hunter-real-facts",
        "pistol-shrimp-bubble-gun",
        "two-factor-auth-why-matters",
    }
)

SEED_TOPICS: list[dict] = [
    {
        "slug": "sleep-clears-brain-waste",
        "title": "Sleep Literally Washes Toxic Waste Out of Your Brain",
        "description": "During deep sleep, the glymphatic system flushes metabolic byproducts like beta-amyloid. Skipping sleep lets waste accumulate — a key reason rest matters for cognition.",
        "category": "Human Brain",
        "difficulty": "medium",
        "evergreen_score": 92,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 52,
        "target_audience": "Health-conscious adults 25-45",
        "notes": "Use simple animation of fluid flow through brain tissue.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "default-mode-network-daydream",
        "title": "What Your Brain Does When You're 'Doing Nothing'",
        "description": "The default mode network activates during rest and drives mind-wandering, memory replay, and future planning. It's not idle — it's doing deep background work.",
        "category": "Human Brain",
        "difficulty": "medium",
        "evergreen_score": 78,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 48,
        "target_audience": "Mindfulness-curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "brain-freeze-fast-explanation",
        "title": "Why Ice Cream Gives You Brain Freeze in Seconds",
        "description": "Cold hits the palate and triggers rapid vasodilation in arteries near the brain, causing sharp pain. Pressing your tongue to the roof of your mouth warms the area and stops it fast.",
        "category": "Human Brain",
        "difficulty": "easy",
        "evergreen_score": 82,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 35,
        "target_audience": "General audience all ages",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "why-yawns-are-contagious",
        "title": "Why Watching Someone Else Yawn Makes You Yawn Too",
        "description": "Contagious yawning is linked to social mirroring and empathy circuits, though the classic 'mirror neuron explains empathy' story is oversimplified. Focus on the yawn cascade everyone recognizes.",
        "category": "Human Brain",
        "difficulty": "medium",
        "evergreen_score": 68,
        "curiosity_score": 78,
        "viral_potential": "medium",
        "estimated_duration_seconds": 46,
        "target_audience": "Psychology-interested adults",
        "notes": None,
        "is_featured": False,
        "priority": "C",
        "production_wave": 4,
    },
    {
        "slug": "working-memory-seven-items",
        "title": "Why You Can Only Hold About 4 Things in Mind at Once",
        "description": "Working memory capacity is limited to roughly four chunks, not seven. Chunking information — like grouping digits into phone-number patterns — expands what you can hold.",
        "category": "Human Brain",
        "difficulty": "easy",
        "evergreen_score": 80,
        "curiosity_score": 79,
        "viral_potential": "medium",
        "estimated_duration_seconds": 40,
        "target_audience": "Students and professionals",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "why-we-forget-dreams",
        "title": "Why You Forget 95% of Your Dreams Within Minutes",
        "description": "Dream memories fade fast because the brain suppresses hippocampal encoding during REM sleep. Learn why keeping a dream journal works only if you write within 60 seconds of waking.",
        "category": "Human Brain",
        "difficulty": "easy",
        "evergreen_score": 90,
        "curiosity_score": 93,
        "viral_potential": "high",
        "estimated_duration_seconds": 45,
        "target_audience": "Curious adults 18-35",
        "notes": "Open with a relatable 'last night I dreamed…' hook.",
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "why-10-percent-brain-myth-is-wrong",
        "title": "Why the 'You Only Use 10% of Your Brain' Myth Is Totally Wrong",
        "description": "The popular myth is wrong: brain scans show nearly every region active over a day. The truth is about efficiency, not unused capacity.",
        "category": "Human Brain",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 42,
        "target_audience": "General science curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "brain-energy-glucose-demand",
        "title": "Your Brain Burns 20% of Your Calories While You Sit Still",
        "description": "Despite being only 2% of body weight, the brain consumes roughly 20% of daily energy, mostly as glucose. Intense thinking slightly increases demand — but not as much as myths claim.",
        "category": "Human Brain",
        "difficulty": "hard",
        "evergreen_score": 80,
        "curiosity_score": 78,
        "viral_potential": "low",
        "estimated_duration_seconds": 50,
        "target_audience": "Fitness and nutrition curious",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "neuroplasticity-adult-brain",
        "title": "Your Brain Rewires Itself Every Day — Even as an Adult",
        "description": "Neuroplasticity lets neurons form new connections through learning, injury recovery, and habit change. Small daily practice literally reshapes your brain.",
        "category": "Human Brain",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 82,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "Self-improvement seekers 20-40",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "cognitive-bias-confirmation",
        "title": "Your Brain Secretly Ignores Facts That Disagree With You",
        "description": "Confirmation bias makes you seek and remember evidence that supports existing beliefs. Awareness of this filter is the first step to thinking more clearly.",
        "category": "Human Brain",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 44,
        "target_audience": "Critical thinkers 18-40",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 3,
    },
    {
        "slug": "placebo-effect-real-changes",
        "title": "Fake Pills Can Trigger Real Healing in Your Body",
        "description": "Placebos activate the same neural pathways as active drugs, releasing endorphins and changing pain perception. Expectation alone can produce measurable physiological effects.",
        "category": "Psychology",
        "difficulty": "medium",
        "evergreen_score": 90,
        "curiosity_score": 86,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "Health and science curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "pratfall-effect-likability",
        "title": "Making a Small Mistake Can Actually Make People Like You More",
        "description": "The pratfall effect shows competent people become more likable after minor blunders, while less competent people lose appeal. Perfection isn't always the goal.",
        "category": "Psychology",
        "difficulty": "easy",
        "evergreen_score": 76,
        "curiosity_score": 86,
        "viral_potential": "high",
        "estimated_duration_seconds": 36,
        "target_audience": "Young professionals",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "spotlight-effect-social-anxiety",
        "title": "Nobody Notices That Small Embarrassing Thing You Did",
        "description": "The spotlight effect makes you overestimate how much others notice your appearance or mistakes. Studies show observers remember far less than you think.",
        "category": "Psychology",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 91,
        "viral_potential": "high",
        "estimated_duration_seconds": 40,
        "target_audience": "Social-anxiety-aware teens and adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "anchoring-effect-first-number",
        "title": "The First Number You Hear Secretly Controls Your Judgment",
        "description": "Anchoring bias makes initial values — even random ones — skew later estimates. Negotiations, pricing, and salary talks all exploit or suffer from this effect.",
        "category": "Psychology",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 83,
        "viral_potential": "medium",
        "estimated_duration_seconds": 42,
        "target_audience": "Career-focused adults 22-40",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "why-believing-you-can-improve-changes-learning",
        "title": "Why Believing You Can Improve Changes How You Learn",
        "description": "Carol Dweck's research shows that a growth mindset — viewing ability as developable — leads to more effort, resilience, and better outcomes than a fixed mindset.",
        "category": "Psychology",
        "difficulty": "easy",
        "evergreen_score": 70,
        "curiosity_score": 78,
        "viral_potential": "medium",
        "estimated_duration_seconds": 45,
        "target_audience": "Students and parents",
        "notes": None,
        "is_featured": False,
        "priority": "C",
        "production_wave": 4,
    },
    {
        "slug": "bystander-effect-why-people-dont-help",
        "title": "Why Crowds Sometimes Fail to Help in Emergencies",
        "description": "The bystander effect shows that responsibility diffuses when others are present. Knowing this bias helps you act decisively — or assign someone specific to call for help.",
        "category": "Psychology",
        "difficulty": "medium",
        "evergreen_score": 82,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 52,
        "target_audience": "Socially conscious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "dunning-kruger-effect-explained",
        "title": "Why Incompetent People Think They're Experts",
        "description": "The Dunning-Kruger effect describes how low skill often pairs with high confidence, because the skills needed to judge competence are the same ones you lack.",
        "category": "Psychology",
        "difficulty": "medium",
        "evergreen_score": 90,
        "curiosity_score": 93,
        "viral_potential": "high",
        "estimated_duration_seconds": 48,
        "target_audience": "Curious adults 18-35",
        "notes": "Keep tone illustrative, not insulting.",
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "hedonic-treadmill-happiness",
        "title": "Why That New Purchase Won't Make You Happy for Long",
        "description": "The hedonic treadmill means people adapt quickly to positive changes and return to a baseline happiness level. Experiences and relationships tend to outlast material gains.",
        "category": "Psychology",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 85,
        "viral_potential": "high",
        "estimated_duration_seconds": 48,
        "target_audience": "Self-improvement audience 20-35",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 3,
    },
    {
        "slug": "mere-exposure-liking-familiarity",
        "title": "You Like Songs More the More You Hear Them — Here's Why",
        "description": "The mere exposure effect means repeated contact increases preference, even without conscious awareness. Familiarity feels safe, and safety feels good.",
        "category": "Psychology",
        "difficulty": "easy",
        "evergreen_score": 78,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 38,
        "target_audience": "Music and culture fans",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "cognitive-dissonance-behavior-change",
        "title": "Your Brain Hates Holding Two Conflicting Beliefs",
        "description": "Cognitive dissonance creates mental discomfort when actions clash with values, pushing you to change beliefs or justify behavior. It's why rationalization feels so convincing.",
        "category": "Psychology",
        "difficulty": "hard",
        "evergreen_score": 76,
        "curiosity_score": 74,
        "viral_potential": "low",
        "estimated_duration_seconds": 55,
        "target_audience": "Psychology students and enthusiasts",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "neutron-star-teaspoon-weight",
        "title": "A Teaspoon of Neutron Star Weighs 6 Billion Tons",
        "description": "Neutron stars pack more mass than the Sun into a city-sized sphere, crushing matter to nuclear density. A sugar-cube-sized piece would outweigh Mount Everest.",
        "category": "Space",
        "difficulty": "medium",
        "evergreen_score": 94,
        "curiosity_score": 96,
        "viral_potential": "high",
        "estimated_duration_seconds": 42,
        "target_audience": "Physics-curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "one-year-on-mars-length",
        "title": "A Year on Mars Lasts Nearly Twice as Long as Earth's",
        "description": "Mars takes about 687 Earth days to orbit the Sun, making a Martian year roughly 1.88 Earth years. Seasons there are longer and more elliptical than ours.",
        "category": "Space",
        "difficulty": "easy",
        "evergreen_score": 80,
        "curiosity_score": 78,
        "viral_potential": "medium",
        "estimated_duration_seconds": 38,
        "target_audience": "Space fans all ages",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "international-space-station-speed",
        "title": "Astronauts on the ISS Experience 16 Sunrises Every Day",
        "description": "The ISS orbits Earth every 90 minutes at roughly 28,000 km/h, cycling through day and night that fast. Microgravity isn't zero gravity — it's continuous freefall.",
        "category": "Space",
        "difficulty": "easy",
        "evergreen_score": 86,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 44,
        "target_audience": "STEM students and space fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "does-jupiter-protect-earth-from-asteroids",
        "title": "Does Jupiter Really Protect Earth From Asteroids?",
        "description": "Jupiter's massive gravity captures or deflects many asteroids and comets that might otherwise hit inner planets. It's not perfect protection, but it reduces impact frequency.",
        "category": "Space",
        "difficulty": "medium",
        "evergreen_score": 74,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 46,
        "target_audience": "Space enthusiasts 15-40",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "space-is-silent-no-air",
        "title": "Explosions in Space Would Be Completely Silent",
        "description": "Sound needs a medium to travel. The vacuum of space has no air, so shock waves can't propagate — which is why sci-fi battle sounds are Hollywood fiction.",
        "category": "Space",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 86,
        "viral_potential": "high",
        "estimated_duration_seconds": 35,
        "target_audience": "Sci-fi fans and general audience",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "moon-drifting-away-earth",
        "title": "The Moon Is Slowly Moving Away From Earth Every Year",
        "description": "Tidal forces transfer angular momentum from Earth to the Moon, pushing it outward about 3.8 cm per year. In billions of years, total solar eclipses will no longer occur.",
        "category": "Space",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "medium",
        "estimated_duration_seconds": 48,
        "target_audience": "Astronomy curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "light-minute-sun-delay",
        "title": "The Sun You See Is Already 8 Minutes Old",
        "description": "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth at 299,792 km/s. If the Sun vanished, we'd still see it briefly before darkness arrived.",
        "category": "Space",
        "difficulty": "easy",
        "evergreen_score": 90,
        "curiosity_score": 88,
        "viral_potential": "medium",
        "estimated_duration_seconds": 40,
        "target_audience": "General science curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "venus-hotter-than-mercury",
        "title": "Venus Is Hotter Than Mercury Despite Being Farther From the Sun",
        "description": "Venus's thick carbon dioxide atmosphere traps heat via a runaway greenhouse effect, pushing surface temperatures above 460°C — hot enough to melt lead.",
        "category": "Space",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 86,
        "viral_potential": "medium",
        "estimated_duration_seconds": 45,
        "target_audience": "Climate and space curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "why-sky-is-dark-at-night",
        "title": "Why Is the Night Sky Dark If the Universe Is Infinite?",
        "description": "Olbers' paradox asks why starlight doesn't fill every patch of sky. The answer involves an expanding universe, finite age, and redshift — not dust blocking light.",
        "category": "Space",
        "difficulty": "hard",
        "evergreen_score": 88,
        "curiosity_score": 94,
        "viral_potential": "high",
        "estimated_duration_seconds": 58,
        "target_audience": "Astronomy curious adults",
        "notes": "Featured deep-space visual recommended.",
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "gold-from-neutron-star-collisions",
        "title": "Your Gold Jewelry Came From Colliding Neutron Stars",
        "description": "Heavy elements like gold and platinum form in kilonova explosions when neutron stars merge. Earth's gold is ancient stardust forged in violent cosmic events.",
        "category": "Space",
        "difficulty": "hard",
        "evergreen_score": 92,
        "curiosity_score": 93,
        "viral_potential": "high",
        "estimated_duration_seconds": 52,
        "target_audience": "Science and jewelry curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "ring-of-fire-earthquakes",
        "title": "90% of Earth's Earthquakes Happen in One Ring",
        "description": "The Pacific Ring of Fire follows tectonic plate boundaries where subduction creates volcanoes and seismic activity. It encircles the Pacific Ocean from Japan to Chile.",
        "category": "Earth",
        "difficulty": "medium",
        "evergreen_score": 80,
        "curiosity_score": 78,
        "viral_potential": "medium",
        "estimated_duration_seconds": 45,
        "target_audience": "Geology students and curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "antarctica-desert-driest",
        "title": "Antarctica Is the World's Largest Desert",
        "description": "Deserts are defined by low precipitation, not heat. Antarctica receives minimal snowfall and has dry valleys where it hasn't rained for millions of years.",
        "category": "Earth",
        "difficulty": "easy",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 40,
        "target_audience": "Geography curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "earth-inner-core-spin",
        "title": "Earth's Inner Core May Spin Faster Than the Rest of the Planet",
        "description": "Seismic wave studies suggest the solid inner core rotates slightly differently from the mantle, possibly completing an extra rotation every few decades.",
        "category": "Earth",
        "difficulty": "hard",
        "evergreen_score": 72,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 55,
        "target_audience": "Geology curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "C",
        "production_wave": 4,
    },
    {
        "slug": "earth-magnetic-field-flips",
        "title": "Earth's Magnetic Poles Flip — and We're Overdue",
        "description": "Geomagnetic reversals happen irregularly, with the last one about 780,000 years ago. During a flip, the field weakens temporarily, letting more solar radiation reach the surface.",
        "category": "Earth",
        "difficulty": "hard",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "medium",
        "estimated_duration_seconds": 52,
        "target_audience": "Science curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "lightning-hotter-than-sun-surface",
        "title": "Lightning Is 5 Times Hotter Than the Surface of the Sun",
        "description": "A lightning bolt channel can reach roughly 30,000°C, compared to about 5,500°C on the Sun's surface. The flash is brief but intensely energetic.",
        "category": "Earth",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 93,
        "viral_potential": "high",
        "estimated_duration_seconds": 38,
        "target_audience": "Weather curious all ages",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "mount-everest-not-tallest",
        "title": "Mount Everest Isn't the Tallest Mountain on Earth",
        "description": "Measured from base to peak, Mauna Kea in Hawaii is taller — most of it hidden underwater. Everest wins only when measuring above sea level.",
        "category": "Earth",
        "difficulty": "easy",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 38,
        "target_audience": "Geography trivia fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "water-older-than-sun",
        "title": "Some Water on Earth Predates the Sun Itself",
        "description": "Heavy water molecules formed in interstellar ice grains before the solar system coalesced. Earth inherited ancient cosmic water during planet formation.",
        "category": "Earth",
        "difficulty": "hard",
        "evergreen_score": 90,
        "curiosity_score": 91,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "Cosmology and Earth science fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "amazon-rain-forest-oxygen-myth",
        "title": "The Amazon Doesn't Produce 20% of Earth's Oxygen",
        "description": "Rainforests consume nearly as much oxygen as they produce through respiration and decomposition. Most breathable oxygen comes from ocean phytoplankton, not trees alone.",
        "category": "Earth",
        "difficulty": "medium",
        "evergreen_score": 90,
        "curiosity_score": 91,
        "viral_potential": "high",
        "estimated_duration_seconds": 46,
        "target_audience": "Environmentally conscious adults",
        "notes": "Myth-bust format works well.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "why-ocean-waves-glow-blue-at-night",
        "title": "Why Some Ocean Waves Glow Blue at Night",
        "description": "Some dinoflagellates emit blue light when waves disturb them. The glow is bioluminescence — not the same as harmful algal bloom headlines.",
        "category": "Earth",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 92,
        "viral_potential": "high",
        "estimated_duration_seconds": 42,
        "target_audience": "Travel and nature lovers",
        "notes": "Use stunning bioluminescence B-roll if available.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "why-deepest-ocean-could-crush-submarine",
        "title": "Why the Deepest Ocean Could Crush a Submarine Instantly",
        "description": "At the Mariana Trench's deepest point, pressure exceeds 1,000 atmospheres — like having 50 jumbo jets stacked on your head. Life there adapts with flexible membranes and special proteins.",
        "category": "Earth",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 48,
        "target_audience": "Ocean and adventure curious",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "periodic-table-gaps-predicted",
        "title": "Mendeleev Predicted Elements That Didn't Exist Yet",
        "description": "Mendeleev left gaps in his periodic table for undiscovered elements and predicted their properties accurately. Gallium and germanium later confirmed his framework.",
        "category": "Science",
        "difficulty": "medium",
        "evergreen_score": 80,
        "curiosity_score": 78,
        "viral_potential": "low",
        "estimated_duration_seconds": 48,
        "target_audience": "Chemistry students",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "double-slit-experiment-intro",
        "title": "Particles Behave Like Waves Until You Watch Them",
        "description": "The double-slit experiment shows electrons creating interference patterns — unless observed, when they act like particles. It's a gateway to quantum weirdness.",
        "category": "Science",
        "difficulty": "hard",
        "evergreen_score": 82,
        "curiosity_score": 94,
        "viral_potential": "high",
        "estimated_duration_seconds": 58,
        "target_audience": "Quantum-curious adults",
        "notes": "Keep explanation intuitive; avoid heavy math.",
        "is_featured": True,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "penicillin-accidental-discovery",
        "title": "Penicillin Was Discovered Because of a Messy Lab",
        "description": "Alexander Fleming noticed mold killing bacteria on a forgotten petri dish in 1928. The accident launched modern antibiotics and saved millions of lives.",
        "category": "Science",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 42,
        "target_audience": "History of science fans",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "carbon-dating-limits",
        "title": "Radiocarbon Dating Can't Date Dinosaur Bones",
        "description": "Carbon-14 decays with a 5,730-year half-life, making it useful for objects up to about 50,000 years old. Older specimens need methods like uranium-lead dating.",
        "category": "Science",
        "difficulty": "medium",
        "evergreen_score": 80,
        "curiosity_score": 76,
        "viral_potential": "low",
        "estimated_duration_seconds": 48,
        "target_audience": "Archaeology curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "supercooled-water-below-freezing",
        "title": "Water Can Stay Liquid Below 0°C Without Freezing",
        "description": "Supercooled water lacks nucleation sites to start crystallization, remaining liquid until disturbed. Tap the bottle and it freezes instantly before your eyes.",
        "category": "Science",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 40,
        "target_audience": "Demo-loving science fans",
        "notes": "Film a supercooling demo if possible.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "why-airplane-wings-dont-work-like-textbook",
        "title": "Why Airplane Wings Don't Work the Way Your Textbook Said",
        "description": "Textbook Bernoulli-only explanations miss angle of attack and Newton's third law. Modern aerodynamics uses pressure differences and downward momentum of air together.",
        "category": "Science",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 50,
        "target_audience": "Students and science-curious adults",
        "notes": "Replacement for oversimplified Bernoulli flight topic (audit REMOVE).",
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "water-expands-when-frozen",
        "title": "Why Ice Floats — and Why That Saves Life on Earth",
        "description": "Water is one of few substances that expands when frozen, making ice less dense than liquid water. Floating ice insulates lakes and oceans, protecting aquatic life in winter.",
        "category": "Science",
        "difficulty": "easy",
        "evergreen_score": 90,
        "curiosity_score": 86,
        "viral_potential": "medium",
        "estimated_duration_seconds": 44,
        "target_audience": "General science curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "why-nothing-can-outrun-light",
        "title": "Why Nothing in the Universe Can Outrun Light",
        "description": "The speed of light in a vacuum is a universal speed limit baked into spacetime. As objects accelerate, relativistic effects prevent reaching or exceeding c.",
        "category": "Science",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "Physics curious 16-40",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "absolute-zero-unreachable",
        "title": "Why Scientists Can Never Reach Absolute Zero",
        "description": "Absolute zero at −273.15°C is a theoretical limit where particle motion stops. The third law of thermodynamics makes reaching it in finite steps impossible.",
        "category": "Science",
        "difficulty": "hard",
        "evergreen_score": 78,
        "curiosity_score": 80,
        "viral_potential": "low",
        "estimated_duration_seconds": 55,
        "target_audience": "Physics enthusiasts",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "entropy-always-increases",
        "title": "Why Your Room Gets Messy But Never Cleans Itself",
        "description": "The second law of thermodynamics says entropy in a closed system tends to increase. Order requires energy input — which is why cleaning takes effort.",
        "category": "Science",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "medium",
        "estimated_duration_seconds": 46,
        "target_audience": "Relatable science audience",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "ai-neural-network-inspired-brain",
        "title": "AI 'Neural Networks' Are Loosely Inspired by Brains — Very Loosely",
        "description": "Artificial neurons are simplified math functions, not biological replicas. Modern deep learning scales computation rather than mimicking actual neural biology.",
        "category": "Technology",
        "difficulty": "medium",
        "evergreen_score": 88,
        "curiosity_score": 86,
        "viral_potential": "high",
        "estimated_duration_seconds": 50,
        "target_audience": "AI-curious adults 18-40",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "bluetooth-named-viking-king",
        "title": "Bluetooth Is Named After a 10th-Century Viking King",
        "description": "The wireless standard's name honors Harald Bluetooth, who united Danish tribes — symbolizing connection. The logo merges Nordic runes for H and B.",
        "category": "Technology",
        "difficulty": "easy",
        "evergreen_score": 78,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 38,
        "target_audience": "Tech trivia fans",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "moores-law-slowing",
        "title": "Computer Chips Can't Keep Shrinking Forever",
        "description": "Moore's Law observed transistor density doubling roughly every two years, but physical limits at nanometer scales are slowing progress. New architectures like 3D stacking extend gains.",
        "category": "Technology",
        "difficulty": "hard",
        "evergreen_score": 78,
        "curiosity_score": 74,
        "viral_potential": "low",
        "estimated_duration_seconds": 55,
        "target_audience": "Semiconductor industry curious",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "gps-needs-relativity",
        "title": "GPS Would Fail in Minutes Without Einstein's Relativity",
        "description": "Satellite clocks run faster in weaker gravity and slower due to orbital speed. Without relativistic corrections, GPS drift would accumulate kilometers of error daily.",
        "category": "Technology",
        "difficulty": "hard",
        "evergreen_score": 92,
        "curiosity_score": 92,
        "viral_potential": "high",
        "estimated_duration_seconds": 52,
        "target_audience": "Physics and tech enthusiasts",
        "notes": "Strong crossover appeal with Science category.",
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "how-phone-fingerprint-sensor-sees-you",
        "title": "How Your Phone's Fingerprint Sensor Actually Sees You",
        "description": "Capacitive fingerprint sensors map ridges as tiny capacitors; ultrasonic sensors bounce sound through skin. Spoof resistance comes from liveness checks, not just the print pattern.",
        "category": "Technology",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 87,
        "viral_potential": "high",
        "estimated_duration_seconds": 45,
        "target_audience": "Tech-curious adults 18-40",
        "notes": "Replacement for password/2FA advice topic (audit REMOVE).",
        "is_featured": False,
        "priority": "A",
        "production_wave": 3,
    },
    {
        "slug": "how-hard-drive-reads-data-without-touching",
        "title": "How a Hard Drive Reads Data Without Touching the Disk",
        "description": "Hard drives use rapidly spinning platters and a magnetic read/write head floating nanometers above the surface. SSDs skip moving parts entirely, using flash memory cells.",
        "category": "Technology",
        "difficulty": "easy",
        "evergreen_score": 72,
        "curiosity_score": 74,
        "viral_potential": "low",
        "estimated_duration_seconds": 45,
        "target_audience": "Computer basics learners",
        "notes": None,
        "is_featured": False,
        "priority": "C",
        "production_wave": 4,
    },
    {
        "slug": "fiber-optic-total-internal-reflection",
        "title": "Internet Cables Send Light, Not Electricity",
        "description": "Fiber optics transmit data as light pulses bouncing through glass via total internal reflection. A single fiber can carry terabits of data across oceans.",
        "category": "Technology",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 80,
        "viral_potential": "low",
        "estimated_duration_seconds": 48,
        "target_audience": "Internet infrastructure curious",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "qr-code-error-correction",
        "title": "QR Codes Still Work Even When Partly Damaged",
        "description": "Reed-Solomon error correction lets QR codes recover data when up to 30% of the code is obscured or damaged. That's why logos can sit in the center.",
        "category": "Technology",
        "difficulty": "medium",
        "evergreen_score": 82,
        "curiosity_score": 82,
        "viral_potential": "medium",
        "estimated_duration_seconds": 44,
        "target_audience": "Tech-curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "why-undersea-cables-carry-almost-all-internet",
        "title": "Why Undersea Cables Carry Almost All Internet Traffic",
        "description": "Satellites handle a tiny fraction of global bandwidth. Fiber-optic cables on the ocean floor move nearly all intercontinental internet as pulses of light.",
        "category": "Technology",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 42,
        "target_audience": "General science and tech curious",
        "notes": "Replacement for cloud-meme topic (audit REMOVE).",
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "touchscreen-capacitive-sensing",
        "title": "Your Finger Doesn't Press a Touchscreen — It Disrupts Electricity",
        "description": "Capacitive screens detect changes in an electrostatic field caused by conductive objects like fingers. Gloves fail because they block that conductivity.",
        "category": "Technology",
        "difficulty": "easy",
        "evergreen_score": 86,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 40,
        "target_audience": "Everyday tech curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 3,
    },
    {
        "slug": "cleopatra-closer-to-moon-landing",
        "title": "Cleopatra Lived Closer to the Moon Landing Than the Pyramids",
        "description": "Cleopatra ruled around 30 BCE, about 2,500 years after the Great Pyramid was built — but only 2,000 years before Apollo 11. Ancient history spans vast time scales.",
        "category": "History",
        "difficulty": "easy",
        "evergreen_score": 94,
        "curiosity_score": 95,
        "viral_potential": "high",
        "estimated_duration_seconds": 40,
        "target_audience": "Timeline-mind-blown audience",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "printing-press-not-first-printing",
        "title": "Gutenberg Didn't Invent Printing — He Made It Fast",
        "description": "Woodblock printing existed in China centuries earlier. Gutenberg's breakthrough was movable metal type and a press system enabling mass production in Europe.",
        "category": "History",
        "difficulty": "medium",
        "evergreen_score": 82,
        "curiosity_score": 78,
        "viral_potential": "low",
        "estimated_duration_seconds": 48,
        "target_audience": "Book and history lovers",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "iron-maiden-torture-myth",
        "title": "Medieval Iron Maidens Were Probably Fake",
        "description": "Most 'iron maiden' devices in museums were 18th–19th century fabrications for sensational exhibitions. There's little reliable medieval evidence for their use.",
        "category": "History",
        "difficulty": "medium",
        "evergreen_score": 78,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 46,
        "target_audience": "Medieval history curious",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "oxford-university-older-than-aztec",
        "title": "Oxford University Is Older Than the Aztec Empire",
        "description": "Teaching at Oxford began by 1096, while the Aztec Empire rose in the 1420s. Some European institutions predate civilizations many assume are ancient.",
        "category": "History",
        "difficulty": "easy",
        "evergreen_score": 92,
        "curiosity_score": 93,
        "viral_potential": "high",
        "estimated_duration_seconds": 40,
        "target_audience": "Timeline comparison fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "salem-witch-trials-no-burning",
        "title": "Salem 'Witches' Were Hanged, Not Burned at the Stake",
        "description": "Nineteen people were executed by hanging during the 1692 Salem witch trials. Burning was more associated with European witch persecutions, not colonial Massachusetts.",
        "category": "History",
        "difficulty": "medium",
        "evergreen_score": 78,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 44,
        "target_audience": "American history students",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "library-of-alexandria-myth",
        "title": "The Library of Alexandria Didn't End Knowledge Forever",
        "description": "Multiple fires and declines eroded the library over centuries, but many texts existed in copies elsewhere. Its loss was significant but not a single catastrophic erasure of all wisdom.",
        "category": "History",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 88,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "History buffs 18-45",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "shortest-war-38-minutes",
        "title": "The Shortest War in History Lasted 38 Minutes",
        "description": "The Anglo-Zanzibar War of 1896 ended in under an hour after British naval bombardment. Sultan Khalid bin Barghash surrendered after his forces were overwhelmed.",
        "category": "History",
        "difficulty": "easy",
        "evergreen_score": 82,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 42,
        "target_audience": "History trivia lovers",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "viking-horned-helmets-myth",
        "title": "Vikings Never Wore Horned Helmets in Battle",
        "description": "Horned helmets come from 19th-century Romantic art and opera costumes, not archaeological evidence. Real Viking helmets were practical, close-fitting iron or leather caps.",
        "category": "History",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 36,
        "target_audience": "History and pop-culture fans",
        "notes": "Myth-bust with strong visual contrast.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "why-we-still-dont-know-who-invented-zero",
        "title": "Why We Still Don't Know Who Invented Zero",
        "description": "The numeral zero emerged through centuries of Mesopotamian placeholders and Indian mathematics. Pinning invention to one person oversimplifies a long cultural evolution.",
        "category": "History",
        "difficulty": "medium",
        "evergreen_score": 85,
        "curiosity_score": 89,
        "viral_potential": "high",
        "estimated_duration_seconds": 48,
        "target_audience": "History and math curious",
        "notes": "Replacement for Lincoln bartender trivia (audit REMOVE).",
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "great-wall-not-visible-from-space",
        "title": "You Can't See the Great Wall of China From Space With Naked Eyes",
        "description": "The wall is narrow and blends with terrain, making it nearly invisible from low Earth orbit without magnification. Many man-made structures are easier to spot.",
        "category": "History",
        "difficulty": "easy",
        "evergreen_score": 86,
        "curiosity_score": 86,
        "viral_potential": "high",
        "estimated_duration_seconds": 38,
        "target_audience": "Myth-busters and trivia fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "honeybee-waggle-dance",
        "title": "Bees Communicate With a Dance That Maps Distance and Direction",
        "description": "Forager bees perform a waggle dance indicating food location relative to the Sun. The angle and duration encode direction and distance for nestmates.",
        "category": "Animals",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 86,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "Nature documentary fans",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "crows-remember-faces",
        "title": "Crows Hold Grudges and Tell Their Friends About You",
        "description": "Crows recognize human faces and pass that information to flockmates. Studies show they scold and mob people who previously trapped them, years later.",
        "category": "Animals",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 91,
        "viral_potential": "high",
        "estimated_duration_seconds": 44,
        "target_audience": "Bird lovers and general audience",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "flamingo-pink-from-diet",
        "title": "Flamingos Aren't Born Pink — They Eat Their Way to It",
        "description": "Flamingo feathers get their color from carotenoid pigments in algae and crustaceans. Without that diet, their plumage fades to white or pale gray.",
        "category": "Animals",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 38,
        "target_audience": "Kids and family audience",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "how-axolotls-regrow-brain-and-heart",
        "title": "How Axolotls Regrow Their Brain and Heart",
        "description": "Axolotls regenerate limbs, spinal cord, heart tissue, and parts of their brain without scarring. Scientists study them for regenerative medicine breakthroughs.",
        "category": "Animals",
        "difficulty": "medium",
        "evergreen_score": 90,
        "curiosity_score": 90,
        "viral_potential": "medium",
        "estimated_duration_seconds": 48,
        "target_audience": "Biology and medical curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "how-tardigrades-survive-vacuum-of-space",
        "title": "How Tardigrades Survive the Vacuum of Space",
        "description": "Tardigrades endure radiation, freezing, boiling, and vacuum by entering cryptobiosis — replacing water in cells with protective glass-like proteins.",
        "category": "Animals",
        "difficulty": "medium",
        "evergreen_score": 92,
        "curiosity_score": 94,
        "viral_potential": "high",
        "estimated_duration_seconds": 46,
        "target_audience": "Microbiology curious adults",
        "notes": "Microscope footage would elevate production.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "octopus-three-hearts",
        "title": "Octopuses Have 3 Hearts and Blue Blood",
        "description": "Two hearts pump blood to the gills and one to the body. Their blood uses copper-based hemocyanin instead of iron hemoglobin, giving it a blue color.",
        "category": "Animals",
        "difficulty": "easy",
        "evergreen_score": 92,
        "curiosity_score": 94,
        "viral_potential": "high",
        "estimated_duration_seconds": 42,
        "target_audience": "Nature lovers all ages",
        "notes": None,
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "platypus-electroreception",
        "title": "Platypuses Hunt Using Built-In Electric Sensors",
        "description": "Platypuses detect prey by sensing electrical signals from muscle contractions with bill receptors. They close their eyes, ears, and nostrils while diving to rely on electroreception.",
        "category": "Animals",
        "difficulty": "medium",
        "evergreen_score": 88,
        "curiosity_score": 90,
        "viral_potential": "medium",
        "estimated_duration_seconds": 46,
        "target_audience": "Weird-animal fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "sloth-slow-metabolism-advantage",
        "title": "Sloths Are Slow on Purpose — It's Their Survival Strategy",
        "description": "Sloths move slowly to conserve energy on a low-calorie leaf diet and avoid predator detection. Their fur hosts algae that provides camouflage.",
        "category": "Animals",
        "difficulty": "easy",
        "evergreen_score": 80,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 40,
        "target_audience": "Casual nature viewers",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "why-cats-always-land-on-their-feet",
        "title": "Why Cats Always Land on Their Feet",
        "description": "The righting reflex lets cats twist mid-air using conservation of angular momentum — no single rigid rotation required. Vestibular sensors trigger the spine to corkscrew before paws hit.",
        "category": "Animals",
        "difficulty": "medium",
        "evergreen_score": 88,
        "curiosity_score": 91,
        "viral_potential": "high",
        "estimated_duration_seconds": 45,
        "target_audience": "General curiosity 16-40",
        "notes": "Replacement for merged pistol-shrimp near-duplicate (audit MERGE).",
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "why-mantis-shrimp-punches-faster-than-bullet",
        "title": "Why the Mantis Shrimp Punches Faster Than a Bullet",
        "description": "Mantis shrimp strike with accelerations over 10,000 g, creating cavitation bubbles that produce light and heat. Their complex eyes see polarized and ultraviolet light.",
        "category": "Animals",
        "difficulty": "medium",
        "evergreen_score": 90,
        "curiosity_score": 93,
        "viral_potential": "high",
        "estimated_duration_seconds": 48,
        "target_audience": "Marine biology fans",
        "notes": "Canonical crustacean-weapons Short after pistol-shrimp merge; emphasize punch speed and cavitation, not a second shrimp species.",
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "goosebumps-vestigial-reflex",
        "title": "Goosebumps Are a Useless Gift From Your Ancestors",
        "description": "Arrector pili muscles pull hair upright to trap warmth — useful for furry mammals, pointless for humans. Strong emotions still trigger the ancient reflex.",
        "category": "Human Body",
        "difficulty": "easy",
        "evergreen_score": 80,
        "curiosity_score": 82,
        "viral_potential": "medium",
        "estimated_duration_seconds": 36,
        "target_audience": "Evolution curious teens and adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "hair-nails-grow-after-death-myth",
        "title": "Hair and Nails Don't Keep Growing After You Die",
        "description": "Dehydration shrinks skin around hair follicles and nail beds, creating an illusion of growth. Cellular activity stops at death, so no new keratin is produced.",
        "category": "Human Body",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 86,
        "viral_potential": "high",
        "estimated_duration_seconds": 38,
        "target_audience": "Myth-busters general audience",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 3,
    },
    {
        "slug": "taste-buds-not-map-zones",
        "title": "The Tongue Taste Map You Learned in School Is Wrong",
        "description": "All basic tastes — sweet, sour, salty, bitter, umami — are detected across the entire tongue. The zone map was a misinterpretation of a 1901 German paper.",
        "category": "Human Body",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 88,
        "viral_potential": "high",
        "estimated_duration_seconds": 40,
        "target_audience": "School myth correction audience",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "what-immune-system-does-in-60-seconds",
        "title": "What Your Immune System Does in the Next 60 Seconds",
        "description": "White blood cells constantly patrol for pathogens, damaged cells, and cancer mutations. Fever, inflammation, and antibodies are coordinated responses to invaders.",
        "category": "Human Body",
        "difficulty": "medium",
        "evergreen_score": 76,
        "curiosity_score": 76,
        "viral_potential": "low",
        "estimated_duration_seconds": 50,
        "target_audience": "Health literacy audience",
        "notes": None,
        "is_featured": False,
        "priority": "C",
        "production_wave": 4,
    },
    {
        "slug": "why-bones-stronger-than-concrete",
        "title": "Why Your Bones Are Stronger Than Concrete — Pound for Pound",
        "description": "Compact bone withstands compression remarkably well for its weight and compares favorably to concrete pound-for-pound. Collagen plus mineral crystal make a tough composite.",
        "category": "Human Body",
        "difficulty": "easy",
        "evergreen_score": 78,
        "curiosity_score": 82,
        "viral_potential": "medium",
        "estimated_duration_seconds": 40,
        "target_audience": "Fitness and anatomy fans",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "why-gut-microbes-shape-digestion-immunity-mood",
        "title": "Why Your Gut Microbes Shape Digestion, Immunity, and Mood",
        "description": "Gut microbes help digest food, train immunity, and communicate with the brain via the gut-brain axis. Avoid outdated 'outnumber your cells 10-to-1' counting claims.",
        "category": "Human Body",
        "difficulty": "medium",
        "evergreen_score": 80,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 48,
        "target_audience": "Health and wellness audience",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "appendix-not-useless",
        "title": "Your Appendix Isn't Useless — It's a Bacteria Safe House",
        "description": "The appendix stores beneficial gut bacteria and may reseed the intestines after diarrhea. Removing it isn't catastrophic, but it's not a meaningless leftover organ.",
        "category": "Human Body",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 44,
        "target_audience": "Medical myth curious",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 3,
    },
    {
        "slug": "blood-travels-full-body",
        "title": "Your Blood Completes a Full Body Loop in About 60 Seconds",
        "description": "The heart pumps roughly 5 liters of blood per minute through 100,000 km of vessels. At rest, a red blood cell circulates the entire body in about one minute.",
        "category": "Human Body",
        "difficulty": "medium",
        "evergreen_score": 84,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 45,
        "target_audience": "Anatomy students and curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "humans-glow-in-dark",
        "title": "Your Body Emits Visible Light — Just Too Faint to See",
        "description": "Human bioluminescence from metabolic reactions produces photons roughly 1,000 times dimmer than naked-eye sensitivity. It's real, but you'd need sensitive cameras to detect it.",
        "category": "Human Body",
        "difficulty": "medium",
        "evergreen_score": 88,
        "curiosity_score": 92,
        "viral_potential": "high",
        "estimated_duration_seconds": 44,
        "target_audience": "Human biology curious",
        "notes": None,
        "is_featured": True,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "stomach-lining-replaces-itself",
        "title": "Your Stomach Lining Replaces Itself Every Few Days",
        "description": "Powerful stomach acid would digest the organ itself without rapid epithelial renewal. New cells migrate up the lining every 3–5 days to maintain the barrier.",
        "category": "Human Body",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 82,
        "viral_potential": "medium",
        "estimated_duration_seconds": 42,
        "target_audience": "Health curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "lichen-two-organisms-one",
        "title": "A Lichen Is Actually Two Organisms Living as One",
        "description": "Lichens are symbiotic partnerships between fungi and algae or cyanobacteria. The fungus provides structure while the photosynthetic partner supplies food.",
        "category": "Biology",
        "difficulty": "easy",
        "evergreen_score": 80,
        "curiosity_score": 80,
        "viral_potential": "low",
        "estimated_duration_seconds": 40,
        "target_audience": "Hikers and nature observers",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "horizontal-gene-transfer-bacteria",
        "title": "Bacteria Can Share Genes With Strangers — No Reproduction Needed",
        "description": "Horizontal gene transfer lets bacteria swap antibiotic resistance and other traits via plasmids. It accelerates evolution far beyond vertical inheritance alone.",
        "category": "Biology",
        "difficulty": "hard",
        "evergreen_score": 80,
        "curiosity_score": 78,
        "viral_potential": "low",
        "estimated_duration_seconds": 50,
        "target_audience": "Microbiology students",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
    {
        "slug": "crispr-gene-editing-scissors",
        "title": "CRISPR Lets Scientists Cut and Paste DNA Like Text",
        "description": "Adapted from bacterial immune systems, CRISPR-Cas9 targets specific DNA sequences for editing. It's revolutionizing medicine, agriculture, and research.",
        "category": "Biology",
        "difficulty": "medium",
        "evergreen_score": 90,
        "curiosity_score": 86,
        "viral_potential": "medium",
        "estimated_duration_seconds": 50,
        "target_audience": "Biotech curious adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "bioluminescence-firefly-chemistry",
        "title": "Fireflies Make Light Without Heat Using a Chemical Reaction",
        "description": "Luciferin and luciferase in firefly abdomens produce cold light through oxidation. Nearly 100% of energy becomes photons, unlike incandescent bulbs that waste most as heat.",
        "category": "Biology",
        "difficulty": "easy",
        "evergreen_score": 84,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 44,
        "target_audience": "Summer nature audience",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 3,
    },
    {
        "slug": "how-immortal-jellyfish-reverses-aging",
        "title": "How This Immortal Jellyfish Reverses Its Aging",
        "description": "Turritopsis dohrnii reverts to a polyp stage when stressed, potentially cycling indefinitely. It's not truly immortal in all conditions, but it's remarkably regenerative.",
        "category": "Biology",
        "difficulty": "medium",
        "evergreen_score": 88,
        "curiosity_score": 92,
        "viral_potential": "high",
        "estimated_duration_seconds": 46,
        "target_audience": "Marine biology and longevity fans",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 1,
    },
    {
        "slug": "how-trees-share-nutrients-fungal-networks",
        "title": "How Trees Share Nutrients Through Underground Fungal Networks",
        "description": "Mycorrhizal fungal networks connect root systems, moving nutrients and chemical cues between trees. Older trees can favor nearby seedlings — without implying trees 'talk' like humans.",
        "category": "Biology",
        "difficulty": "medium",
        "evergreen_score": 86,
        "curiosity_score": 90,
        "viral_potential": "high",
        "estimated_duration_seconds": 48,
        "target_audience": "Nature and ecology fans",
        "notes": "Featured forest visual strongly recommended.",
        "is_featured": True,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "photosynthesis-quantum-efficiency",
        "title": "Plants Use Quantum Physics to Harvest Sunlight",
        "description": "Photosynthetic complexes may use quantum coherence to explore multiple energy pathways simultaneously, achieving near-perfect light conversion efficiency.",
        "category": "Biology",
        "difficulty": "hard",
        "evergreen_score": 65,
        "curiosity_score": 84,
        "viral_potential": "medium",
        "estimated_duration_seconds": 55,
        "target_audience": "Advanced science enthusiasts",
        "notes": None,
        "is_featured": False,
        "priority": "C",
        "production_wave": 4,
    },
    {
        "slug": "dna-if-unraveled-length",
        "title": "The DNA in One Cell Stretches 2 Meters Long",
        "description": "Each human cell packs about 2 meters of DNA into a nucleus roughly 6 micrometers wide. Histone proteins coil and fold it into an ultra-dense structure.",
        "category": "Biology",
        "difficulty": "easy",
        "evergreen_score": 88,
        "curiosity_score": 88,
        "viral_potential": "medium",
        "estimated_duration_seconds": 42,
        "target_audience": "Genetics curious teens and adults",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "mitochondria-bacterial-origin",
        "title": "The Powerhouses of Your Cells Were Once Free-Living Bacteria",
        "description": "Endosymbiotic theory explains mitochondria as ancient bacteria engulfed by early cells. They retain their own DNA and divide independently inside your cells.",
        "category": "Biology",
        "difficulty": "hard",
        "evergreen_score": 88,
        "curiosity_score": 86,
        "viral_potential": "medium",
        "estimated_duration_seconds": 52,
        "target_audience": "Cell biology students",
        "notes": None,
        "is_featured": False,
        "priority": "A",
        "production_wave": 2,
    },
    {
        "slug": "epigenetics-genes-not-destiny",
        "title": "Your Genes Aren't Your Destiny — Switches Turn Them On and Off",
        "description": "Epigenetic marks like DNA methylation control which genes express without changing the sequence. Environment, diet, and stress can alter these switches.",
        "category": "Biology",
        "difficulty": "hard",
        "evergreen_score": 82,
        "curiosity_score": 80,
        "viral_potential": "medium",
        "estimated_duration_seconds": 52,
        "target_audience": "Genetics and wellness audience",
        "notes": None,
        "is_featured": False,
        "priority": "B",
        "production_wave": 4,
    },
]
