"""Pydantic request and response schemas."""

from app.schemas.audit import AuditLogListResponse, AuditLogResponse
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    UserCreate,
    UserResponse,
    normalize_email,
)
from app.schemas.content_version import (
    ApprovalRequestCreate,
    ApprovalResponse,
    ApprovalReviewRequest,
    ContentVersionCreate,
    ContentVersionListResponse,
    ContentVersionResponse,
)
from app.schemas.knowledge_pack import (
    KnowledgePackCreate,
    KnowledgePackListResponse,
    KnowledgePackReorderRequest,
    KnowledgePackResponse,
    KnowledgePackSectionResponse,
    KnowledgePackSectionUpdate,
    KnowledgePackUpdate,
)
from app.schemas.project import (
    CategoryCreate,
    CategoryResponse,
    CategoryUpdate,
    ProjectCreate,
    ProjectListResponse,
    ProjectMemberResponse,
    ProjectResponse,
    ProjectUpdate,
    TagCreate,
    TagResponse,
    TagUpdate,
)
from app.schemas.rbac import (
    MessageResponse,
    PermissionResponse,
    RoleCreate,
    RoleResponse,
)
from app.schemas.script import (
    ScriptCreate,
    ScriptDocumentResponse,
    ScriptDocumentUpdate,
    ScriptListResponse,
    ScriptResponse,
    ScriptUpdate,
)

__all__ = [
    "ApprovalRequestCreate",
    "ApprovalResponse",
    "ApprovalReviewRequest",
    "AuditLogListResponse",
    "AuditLogResponse",
    "CategoryCreate",
    "CategoryResponse",
    "CategoryUpdate",
    "ContentVersionCreate",
    "ContentVersionListResponse",
    "ContentVersionResponse",
    "KnowledgePackCreate",
    "KnowledgePackListResponse",
    "KnowledgePackReorderRequest",
    "KnowledgePackResponse",
    "KnowledgePackSectionResponse",
    "KnowledgePackSectionUpdate",
    "KnowledgePackUpdate",
    "LoginRequest",
    "MessageResponse",
    "PermissionResponse",
    "ProjectCreate",
    "ProjectListResponse",
    "ProjectMemberResponse",
    "ProjectResponse",
    "ProjectUpdate",
    "RoleCreate",
    "RoleResponse",
    "ScriptCreate",
    "ScriptDocumentResponse",
    "ScriptDocumentUpdate",
    "ScriptListResponse",
    "ScriptResponse",
    "ScriptUpdate",
    "TagCreate",
    "TagResponse",
    "TagUpdate",
    "TokenResponse",
    "UserCreate",
    "UserResponse",
    "normalize_email",
]
