"""Controlled knowledge pack status values."""

KNOWLEDGE_PACK_STATUS_DRAFT = "draft"
KNOWLEDGE_PACK_STATUS_ACTIVE = "active"
KNOWLEDGE_PACK_STATUS_ARCHIVED = "archived"

KNOWLEDGE_PACK_STATUSES: frozenset[str] = frozenset(
    {
        KNOWLEDGE_PACK_STATUS_DRAFT,
        KNOWLEDGE_PACK_STATUS_ACTIVE,
        KNOWLEDGE_PACK_STATUS_ARCHIVED,
    }
)

DEFAULT_KNOWLEDGE_PACK_STATUS = KNOWLEDGE_PACK_STATUS_DRAFT
